version: 2

workflows:
    version: 2
    all:
        jobs:
        - test-1.081-devel
        - test-1.081-prod
        - test-2.070-devel
        - test-2.070-prod
        - test-2.071-devel
        - test-2.071-prod
        - test-2.077-upstream-devel
        - test-2.077-upstream-prod
        - d2tag:
            context: org-global
            requires:
            - test-1.081-devel
            - test-1.081-prod
            - test-2.070-devel
            - test-2.070-prod
            - test-2.071-devel
            - test-2.071-prod
            - test-2.077-upstream-devel
            - test-2.077-upstream-prod
            filters:
                tags:
                    ignore: /.*\+d2$/
                branches:
                    ignore: /.*/

templates:
    test: &test-template
        docker:
        - image: sociomantictsunami/dlang:xenial-v3.2.0-rc.1
          user: cachalot
        steps:
        - checkout
        - run:
            name: Update submodules
            command: |
                git submodule sync
                git submodule update --init
        - run:
            name: Install dependencies
            command: sudo -E .circleci/deps.sh
        - run:
            name: Build & run tests
            command: .circleci/test.sh
        - run:
            name: Upload code coverage report
            command: bash <(curl -s https://codecov.io/bash)

jobs:
    test-1.081-devel:
        <<: *test-template
        environment:
        - DMD: "1.081.*"
        - F: "devel"
    test-1.081-prod:
        <<: *test-template
        environment:
        - DMD: "1.081.*"
        - F: "production"
    test-2.070-devel:
        <<: *test-template
        environment:
        - DMD: "2.070.2.s*"
        - F: "devel"
    test-2.070-prod:
        <<: *test-template
        environment:
        - DMD: "2.070.2.s*"
        - F: "production"
    test-2.071-devel:
        <<: *test-template
        environment:
        - DMD: "2.071.2.s*"
        - F: "devel"
    test-2.071-prod:
        <<: *test-template
        environment:
        - DMD: "2.071.2.s*"
        - F: "production"
    test-2.077-upstream-devel:
        <<: *test-template
        environment:
        - DMD: "2.077.*"
        - F: "devel"
    test-2.077-upstream-prod:
        <<: *test-template
        environment:
        - DMD: "2.077.*"
        - F: "production"
    d2tag:
        docker:
        - image: sociomantictsunami/dlang:xenial-v3
          user: cachalot
        steps:
        - checkout
        - run:
            name: Update submodules
            command: |
                git submodule sync
                git submodule update --init
        - run: make d2conv
        - run: .circleci/d2tag.sh
